# Generated by Django 2.2.5 on 2019-09-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='date_of_birth',
        ),
    ]
