# Generated by Django 2.2.5 on 2019-12-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='career_podiums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='career_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='career_poles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='career_races',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='career_seasons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='career_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='season_DNF_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='season_avg_overtakes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='season_beat_teammate_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='season_podiums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='season_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='season_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='season_wins',
            field=models.IntegerField(default=0),
        ),
    ]
